[module/bspwm]
type = internal/bspwm
pin-workspaces = true
enable-scroll = false
format = <label-state> <label-mode>

; Slot States
; -----------

label-empty =
label-focused = %icon%
label-focused-padding-right = 1
label-occupied = %icon%
label-occupied-foreground = ${oil8.cyber-grape}
label-occupied-padding-right = 1
label-urgent = %icon%
label-urgent-background = ${oil8.english-red}
label-urgent-foreground = ${oil8.eerie-black}
label-urgent-padding-right = 1

; Layout / Node-State Modes
; -------------------------

label-tiled = 
label-monocle = 
label-floating = 
label-fullscreen = 
label-pseudotiled = 

label-locked = 
label-sticky = 
label-marked = 
label-private = 

; Workspace Glyph Map
; -------------------

ws-icon-0 = tty;
ws-icon-1 = browse;
ws-icon-2 = d3;3
ws-icon-3 = d4;4
ws-icon-4 = d5;5
ws-icon-5 = d6;6
ws-icon-6 = d7;7
ws-icon-7 = d8;8
ws-icon-8 = d9;9
ws-icon-9 = misc;

ws-icon-10 = tty.x;
ws-icon-11 = browse.x;
ws-icon-12 = d3.x;3
ws-icon-13 = d4.x;4
ws-icon-14 = d5.x;5
ws-icon-15 = d6.x;6
ws-icon-16 = d7.x;7
ws-icon-17 = d8.x;8
ws-icon-18 = d9.x;9
ws-icon-19 = misc.x;
