unbind '%'
unbind '"'
bind | split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'

bind Down  resize-pane -D
bind Left  resize-pane -L
bind Right resize-pane -R
bind Up    resize-pane -U

bind S-Down  resize-pane -D 10
bind S-Left  resize-pane -L 10
bind S-Right resize-pane -R 10
bind S-Up    resize-pane -U 10

# vim: ft=tmux
